# Úkoly

## Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [20]:
import numpy as np
p = print
a = np.array(range(1,11))
print(a)
b = np.random.randint(1,10, (3,3))
p(b)


[ 1  2  3  4  5  6  7  8  9 10]
[[1 4 5]
 [7 5 8]
 [7 2 9]]



1. Vyberte z pole `a` třetí a čtvrtý prvek.


In [21]:
p(a[2])
p(a[3,])

3
4



2. Vyberte z pole `a` všechny sudá čísla.


In [23]:
a[1::2]

array([ 2,  4,  6,  8, 10])


3. Obraťte vektor `a` (první prvek se stane posledním).


In [24]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])


5. Vyberte z pole `b` druhý řádek.


In [32]:
b[1,:]

array([7, 5, 8])


6. Vyberte z pole `b` diagonální prvky.


In [36]:
b.diagonal()

array([1, 5, 9])


7. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.


In [38]:
b[1,0] = 100
b

array([[  1,   4,   5],
       [100,   5,   8],
       [  7,   2,   9]])


8. Vyberte z pole `b` všechny prvky větší než 5.


In [40]:
b[b > 5]

array([100,   8,   7,   9])


9. Vytvořte masku pro pole `b`, která bude True pro všechny prvky menší než 3.


In [43]:
mask = (b < 9)
b[mask]

array([1, 4, 5, 5, 8, 7, 2])


10. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.





## View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.


In [46]:
a = np.random.randint(1,10,(5,5))
p(a)

[[1 1 5 3 1]
 [6 7 8 9 7]
 [5 7 4 6 1]
 [2 4 8 2 3]
 [2 4 6 4 2]]



1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.


In [52]:
b = a[1,0:4]
p(b)

[6 7 8 9]



3. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?


In [53]:
b[0] = 666
p(b)
p(a)

[666   7   8   9]
[[  1   1   5   3   1]
 [666   7   8   9   7]
 [  5   7   4   6   1]
 [  2   4   8   2   3]
 [  2   4   6   4   2]]



4. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.


In [56]:
c = a[1,:].copy()
p(c)

[666   7   8   9   7]



5. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?


In [57]:
c[0] = 20
p(a)

[[  1   1   5   3   1]
 [666   7   8   9   7]
 [  5   7   4   6   1]
 [  2   4   8   2   3]
 [  2   4   6   4   2]]



6. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.


In [58]:
p(id(b))
p(id(c))

140135264009360
140135264438480



7. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.


In [73]:
d = a.diagonal().copy()
p(d)
help(np.diagonal)

[1 7 4 2 2]
Help on _ArrayFunctionDispatcher in module numpy:

diagonal(a, offset=0, axis1=0, axis2=1)
    Return specified diagonals.

    If `a` is 2-D, returns the diagonal of `a` with the given offset,
    i.e., the collection of elements of the form ``a[i, i+offset]``.  If
    `a` has more than two dimensions, then the axes specified by `axis1`
    and `axis2` are used to determine the 2-D sub-array whose diagonal is
    returned.  The shape of the resulting array can be determined by
    removing `axis1` and `axis2` and appending an index to the right equal
    to the size of the resulting diagonals.

    In versions of NumPy prior to 1.7, this function always returned a new,
    independent array containing a copy of the values in the diagonal.

    In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal,
    but depending on this fact is deprecated. Writing to the resulting
    array continues to work as it used to, but a FutureWarning is issued.

    Starting in Nu


8. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?



In [74]:
d[0] = 22
p(d)
p(a)

[22  7  4  2  2]
[[  1   1   5   3   1]
 [666   7   8   9   7]
 [  5   7   4   6   1]
 [  2   4   8   2   3]
 [  2   4   6   4   2]]


9. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Jak je to s pamětí, jedná se o kopii nebo o "array view" ověřte pomocí atributu base.


In [77]:
p(id(a))
e = a.T
p(e)
p(id(e.base))

140135264448656
[[  1 666   5   2   2]
 [  1   7   7   4   4]
 [  5   8   4   8   6]
 [  3   9   6   2   4]
 [  1   7   1   3   2]]
140135264448656




## Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


In [78]:
a = np.random.randint(1,4,(5,3))
b = np.random.randint(5,9,(3,2))
p(a)
p(b)

a @ b

[[2 3 2]
 [1 2 2]
 [1 2 3]
 [2 2 1]
 [3 1 3]]
[[6 7]
 [8 7]
 [8 7]]


array([[52, 49],
       [38, 35],
       [46, 42],
       [36, 35],
       [50, 49]])

2. Vezměme náhodnou matici 10x2 představující kartézské souřadnice, převeďte je na polární souřadnice.


In [82]:
import math
a = np.random.randint(0,11,(10,2))
p(a)

import numpy as np
C = np.random.random((10,2))
X = np.copy(C[:, 0])
Y = np.copy(C[:,1])
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

X,Y = C[:,0], C[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[ 7  6]
 [ 4  2]
 [ 5  6]
 [ 2 10]
 [ 3  9]
 [ 4  2]
 [ 7  8]
 [ 2  5]
 [ 9  7]
 [ 5  3]]
[0.73687178 0.90978201 0.40377412 0.54706395 0.57554606 0.66012425
 0.45470621 1.20989741 0.35661834 0.7426819 ]
[0.98047388 0.08936086 1.42679683 0.39009184 1.49180804 0.21726198
 0.09015753 0.64735545 0.28131915 0.37829924]
[0.73687178 0.90978201 0.40377412 0.54706395 0.57554606 0.66012425
 0.45470621 1.20989741 0.35661834 0.7426819 ]
[0.98047388 0.08936086 1.42679683 0.39009184 1.49180804 0.21726198
 0.09015753 0.64735545 0.28131915 0.37829924]


3. Vzhledem ke dvěma polím X a Y zkonstruujte Cauchyho matici C (Cij =1/(xi - yj)).


4. Uvažujme náhodný vektor o tvaru (100,2) představující souřadnice, najděte vzdálenosti bod po bodu.


5. Ověřte empiricky na náhodné matici, že platí $(AB)^T = B^T A^T$


In [84]:
A = np.random.randint(1,5,(3,3))
B = np.random.randint(1,5,(3,3))

print((A @ B).T)
print(B.T @ A.T)

[[32 17 15]
 [24  9 12]
 [32 11 18]]
[[32 17 15]
 [24  9 12]
 [32 11 18]]


6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$ $$(uv)_{ij} = u_iv_j$$ pomocí `newaxis`. Zkontrolujte s `np.outer(u, v)`


7. Vypočítejte hodnost matice o velikosti 5x6 naplněnou hodnotami 0, 1, 2, 3 ... . Byly by jste schopni zdůvodnit proč je hodnost taková jaká je?



## Funkce nad poli
1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.


2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.



3. Uvažujme celočíselný vektor Z, které z těchto výrazů jsou platné?
   ```python
   Z**Z
   2 << Z >> 2
   Z <- Z
   1j*Z
   Z/1/1
   Z<Z>Z
   ```



4. Jaký je výsledek následujícího výrazu? 
   ```python
   0 * np.nan
   np.nan == np.nan
   np.inf > np.nan
   np.nan - np.nan
   np.nan in set([np.nan])
   0.3 == 3 * 0.1
   ```


In [87]:
p(0 * np.nan)
p(np.nan == np.nan)
p(np.inf > np.nan)
p(np.nan - np.nan)
p(np.nan in set([np.nan]))
p(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


5. Jaké jsou výsledky následujících výrazů?
   ```python
   np.array(0) / np.array(0)
   np.array(0) // np.array(0)
   np.array([np.nan]).astype(int).astype(float)
   ```



6. Jak najít společné (stejné) hodnoty mezi dvěma poli? 



7. Jak vypočítat ((A+B)*(-A/2)) přímo v poli (bez kopírování)?




8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.


In [93]:
A = np.random.randint(1,15,(10))
p(A)
p(np.sort(A))

[13  3 11 10  2  7 11  5  9 11]
[ 2  3  5  7  9 10 11 11 11 13]



9. Vezměme daný vektor, jak přidat 1 ke každému prvku indexovanému druhým vektorem (dejte pozor na opakované indexy)? 

