# Importujeme numpy

Chceme-li použít `numpy`, je samozřejmě nutné modul importovat. Obvykle se použivá zkratka `np`: 


In [4]:
import numpy as np
p =print

# Lineární algebra
Numpy dokáže velice obratně a efektivně pracovat s vektory, maticemi a n-dimenzionálními poli obecně. Toho je potřeba využívat a kdekoli to je možné použít *vektorizovaný kód*, tj. co nejvíce formulovat úlohy pomocí vektorových a maticových operací, jako jsou např. násobení matic.

### Operace se skaláry
Jak bychom asi očekávali, skalárem můžeme násobit, dělit, můžeme ho přičítat nebo odečítat.

In [25]:
v1 = np.arange(0, 3)
p(v1)

[0 1 2]


In [7]:
v1 * 2
p(v1 * 2)

[0 2 4 6 8]


In [8]:
v1 + 2


array([2, 3, 4, 5, 6])

In [9]:
np.ones((3, 3)) * 4


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

## Maticové operace po prvcích
Operace jako násobení, sčítání atd. jsou v numpy standardně *po prvcích*, není to tedy klasická maticová (vektorová) algebra.

In [10]:
m1 = np.array([[n + m * 10 for n in range(5)] for m in range(5)])
m1


array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [11]:
m1 * m1


array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [12]:
v1 * v1


array([ 0,  1,  4,  9, 16])

## Broadcasting
Termín `Broadcasting` popisuje, jak NumPy zachází s poli s různými tvary během aritmetických operací. S výhradou určitých omezení je menší pole „vysíláno“ přes větší pole, takže mají kompatibilní tvary. Broadcasting poskytuje prostředky pro vektorizaci operací pole tak, aby smyčkování probíhalo v C namísto Pythonu. Dělá to bez vytváření zbytečných kopií dat a obvykle vede k efektivní implementaci algoritmů.

Podrobnější popis broadcastingu je v dokumentaci NumPy viz [tady](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

In [26]:
p(v1)
arr = ([1,2,3], [4,5,6], [7,8,9])
p(arr)
m1 = np.array(arr)
p(m1)
v1.shape, m1.shape


[0 1 2]
([1, 2, 3], [4, 5, 6], [7, 8, 9])
[[1 2 3]
 [4 5 6]
 [7 8 9]]


((3,), (3, 3))

Výsledek bude mít rozměr `m1.shape`

In [27]:
v1 * m1


array([[ 0,  2,  6],
       [ 0,  5, 12],
       [ 0,  8, 18]])

## Maticová algebra
Klasickou maticovou algebru zajišťuje pro pole typu `ndarray` funkce `dot` nebo operátor `@` ([PEP-465](https://www.python.org/dev/peps/pep-0465/)):

In [33]:
v1 = np.arange(0, 3)
m1 = np.array([[n + m * 10 for n in range(3)] for m in range(3)])
print(v1)
print(m1)


[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [31]:
# maticové násobení dvou matic
np.dot(m1, m1)


array([[ 50,  53,  56],
       [350, 383, 416],
       [650, 713, 776]])

In [36]:
m1 @ m1


array([[ 50,  53,  56],
       [350, 383, 416],
       [650, 713, 776]])

In [34]:
# maticové násobení vektoru a matice
np.dot(m1, v1)


array([ 5, 35, 65])

In [35]:
# skalární součin
v1 @ v1


5

## Transformace
Už jsme viděli `.T` pro transponování. Existuje také funkce a metoda `transpose`. Dále existuje třeba `conjugate` pro komplexní sdružení.

In [37]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A.T)
print(A.transpose())
print(np.transpose(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
# transpozice je "view"
print(id(A))
B = A.T
print(id(B.base))
p(B.base)

139999756525872
139999756525872
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
C = np.array([[1j, 2j], [3j, 4j]])
print(C+1)


[[1.+1.j 1.+2.j]
 [1.+3.j 1.+4.j]]


In [43]:
np.conjugate(C)      # nebo C.conjugate()


array([[0.-1.j, 0.-2.j],
       [0.-3.j, 0.-4.j]])

In [44]:
# Hermitovské sdružení
C.conjugate().T


array([[0.-1.j, 0.-3.j],
       [0.-2.j, 0.-4.j]])

In [48]:
# Hermitovské sdružení není! "view" kvůli conjugate()
print(C)
B = C.conjugate()
print(B)

[[0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j]]
[[0.-1.j 0.-2.j]
 [0.-3.j 0.-4.j]]


Reálnou a imaginární část dostaneme pomocí `real` a `imag` nebo `.real` a `.imag` properties:

In [49]:
np.real(C)


array([[0., 0.],
       [0., 0.]])

In [50]:
C.imag


array([[1., 2.],
       [3., 4.]])

Komplexní číslo rozložíme na absolutní hodnotu a úhel pomocí `abs` a `angle`.

In [52]:
print(np.abs(C))
# výsledek je v radiánech a všechny hodnoty byly čistě komplexní
print(np.angle(C+1))


[[1. 2.]
 [3. 4.]]
[[0.78539816 1.10714872]
 [1.24904577 1.32581766]]


In [53]:
np.abs(C + 1)


array([[1.41421356, 2.23606798],
       [3.16227766, 4.12310563]])

## Základní funkce lineární algebry

V Numpy existuje modul `linalg`. Pokročilejší lineární algebru je ale třeba hledat jinde, např. ve SciPy. 

Invertovat matici můžeme pomocí `linalg.inv`.

In [55]:
m2 = np.array([[1., 1.5], [-1, 2]])
m2


array([[ 1. ,  1.5],
       [-1. ,  2. ]])

In [64]:
m2 @ np.linalg.inv(m2)
#help(np.eye)
#p(np.eye(3))

array([[1., 0.],
       [0., 1.]])

In [61]:
# toto by měla být jednotková matice
np.linalg.inv(m2) @ m2


array([[1., 0.],
       [0., 1.]])

`linalg.det` vypočítá determinant.

In [65]:
np.linalg.det(m2)


3.5

`linagl.eig` vypočítá vlastní čísla a vlastní vektory matice.

In [67]:
D, U = np.linalg.eig(m2)
print(D)
#print(U)

[1.5+1.11803399j 1.5-1.11803399j]


`linalg.svd` vypočítá singulární rozklad matice.

In [68]:
M = np.arange(12).reshape(3, 4)
print(M)

U, S, V = np.linalg.svd(M)
print(U)
print(S)
print(V)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.1473065   0.90090739  0.40824829]
 [ 0.50027528  0.2881978  -0.81649658]
 [ 0.85324407 -0.32451178  0.40824829]]
[2.24092982e+01 1.95534034e+00 7.68985043e-16]
[[ 0.39390139  0.46087474  0.5278481   0.59482145]
 [-0.73813393 -0.29596363  0.14620666  0.58837696]
 [-0.50775138  0.52390687  0.47544042 -0.4915959 ]
 [-0.20539847  0.65232016 -0.68844492  0.24152322]]
